---
- name: check for available windows updates
  hosts: all
  gather_facts: false
  collections:
    - ansible.windows
  tasks:
    - name: check for available updates
      ansible.windows.win_updates:
        category_names:
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
        state: searched
        log_path: C:\ansible_win_check_updates.txt
      register: winupdates

    - name: print output of winupdates registered variable
      debug:
        msg: "There are {{ winupdates.found_update_count }} available updates"
