---
- name: install windows security updates without rebooting
  hosts: all
  gather_facts: false
  tasks:
    - name: install windows security updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        log_path: C:\ansible_win_sec_updates.txt
        